export const ActionTypes = {
  USER: {
    SET_AUTHENTICATED: "USER.SET_AUTHENTICATED",
    SET_UNAUTHENTICATED: "USER.SET_UNAUTHENTICATED",
    SET_USER: "USER.SET_USER",
    LOADING_USER: "USER.LOADING_USER",
    STOP_LOADING_USER: "USER.STOP_LOADING_USER",
    LOADING_PICTURE: "USER.LOADING_PICTURE",
    STOP_LOADING_PICTURE: "USER.STOP_LOADING_PICTURE",
    VALIDATE_TOKEN: "USER.VALIDATE_TOKEN",
    SET_ERRORS: "USER.SET_ERRORS",
    CLEAR_ERRORS: "USER.CLEAR_ERRORS",
    ENROLL_COMPANY: "USER.ENROLL_COMPANY",
    ENROLL_COMPLETED: "USER.ENROLL_COMPLETED"
  },
  CALL: {
    SET_EMPLOYEE: "CALL.SET_EMPLOYEE",
    LOADING_EMPLOYEE: "CALL.LOADING_EMPLOYEE",
    SET_ERRORS: "CALL.SET_ERRORS",
    CLEAR_ERRORS: "CALL.CLEAR_ERRORS",
    END_CALL: "CALL.END_CALL"
  },
  UI: {
    LOADING_UI: "UI.LOADING_UI",
    STOP_LOADING_UI: "UI.STOP_LOADING_UI",
    SET_ERRORS: "UI.SET_ERRORS",
    CLEAR_ERRORS: "UI.CLEAR_ERRORS"
  }
};
