export const ActionTypes = {
  USER: {
    SET_AUTHENTICATED: "USER.SET_AUTHENTICATED",
    SET_UNAUTHENTICATED: "USER.SET_UNAUTHENTICATED",
    SET_USER: "USER.SET_USER",
    LOADING_USER: "USER.LOADING_USER",
    SET_ERRORS: "USER.SET_ERRORS",
    CLEAR_ERRORS: "USER.CLEAR_ERRORS",
  },
};
